### ISSUE TITLE
Support dockerhub authentication

### ISSUE THREAD

**Issue by wheresrhys** [snyk/snyk-orb#31]
Shortly, dockerhub will start severely rate limiting image pulls for anonymous requests. Unless circleci and dockerhub manage to come to some sort of agreement(it's not clear they will) this means the vast majority of jobs run on a conatainer pulled without auth will fail to initialise. CircleCIs belated advice to all users is to add docker hub authentication to all jobs ([example](https://discuss.circleci.com/t/updated-authenticate-with-docker-to-avoid-impact-of-nov-1st-rate-limits/37567/35)). 

This means orbs will need to be updated to accept passing in dockerhub credentials too. The deadline is 1st November, adn without these changes this orb will, to all intents and purposes, become unusable.

It'd be good to get a response ASAP to answer whether this is likely to be addressed by then.

Thanks in advance

**Comment by JackuB** [comment]
@wheresrhys hi, yes we are aware and planning to address this for our tooling, including this Orb

**Comment by wheresrhys** [comment]
It'd be good to share the API design ASAP as we can start lining up a pull request in our wrapped version of this orb which passes in credentials using the correct property names

**Comment by maxjeffos** [comment]
@wheresrhys I don't think this has any impact on our Orb since our Orb does not use Docker. Unless I'm missing something?

**Comment by wheresrhys** [comment]
You're quite right. I figured out the same myself yesterday afternoon. Thanks for looking into it
