### ISSUE TITLE
Add support for no_output_timeout param

### ISSUE THREAD

**Issue by swarajrao** [snyk/snyk-orb#68]
Some repos take a long time to scan, Circle fails steps that take 10+ minutes without any output. Supporting [no_output_timeout ](https://support.circleci.com/hc/en-us/articles/360045268074-Build-Fails-with-Too-long-with-no-output-exceeded-10m0s-context-deadline-exceeded-) as a param input would help resolve this.
There is currently no way to use `no_output_timeout` on an orb directly.

**Comment by epdl** [comment]
+1
